import type { Profile } from '@/types'

export const mockProfiles: Profile[] = [
  {
    user_id: '9999',
    name: 'Иван',
    age: 27,
    gender: 'male',
    interested_in: 'female',
    about: 'Занимаюсь силовыми, ищу партнёра по тренировкам',
    photos: ['https://i.pravatar.cc/400?img=12'],
    city: 'Москва',
    club: 'FitLife',
    active: true,
    is_blocked: false,
  },
  {
    user_id: '1001',
    name: 'Анна',
    age: 25,
    gender: 'female',
    interested_in: 'male',
    about: 'Люблю кроссфит и здоровое питание',
    photos: ['https://i.pravatar.cc/400?img=1'],
    city: 'Москва',
    club: 'FitLife',
    active: true,
    is_blocked: false,
  },
  {
    user_id: '1002',
    name: 'Мария',
    age: 28,
    gender: 'female',
    interested_in: 'male',
    about: 'Йога и плавание — моё всё',
    photos: ['https://i.pravatar.cc/400?img=2'],
    city: 'Москва',
    club: 'SportCity',
    active: true,
    is_blocked: false,
  },
  {
    user_id: '1003',
    name: 'Елена',
    age: 23,
    gender: 'female',
    interested_in: 'all',
    about: 'Бег и функциональный тренинг',
    photos: ['https://i.pravatar.cc/400?img=3'],
    city: 'Санкт-Петербург',
    club: 'FitLife',
    active: true,
    is_blocked: false,
  },
  {
    user_id: '1004',
    name: 'Дарья',
    age: 30,
    gender: 'female',
    interested_in: 'male',
    about: 'Тяжёлая атлетика и пауэрлифтинг',
    photos: ['https://i.pravatar.cc/400?img=6'],
    city: 'Москва',
    club: 'FitLife',
    active: true,
    is_blocked: false,
  },
  {
    user_id: '1005',
    name: 'Ксения',
    age: 26,
    gender: 'female',
    interested_in: 'male',
    about: 'Зумба и растяжка',
    photos: ['https://i.pravatar.cc/400?img=7'],
    city: 'Казань',
    club: 'ActiveClub',
    active: true,
    is_blocked: false,
  },
  {
    // Заблокированный — не должен появляться в ленте
    user_id: '9998',
    name: 'Заблокированный',
    age: 20,
    gender: 'female',
    interested_in: 'male',
    about: '',
    photos: [],
    city: 'Москва',
    club: 'FitLife',
    active: true,
    is_blocked: true,
  },
]
