import type { Profile } from '@/types'

export const mockProfiles: Profile[] = [
  {
    user_id: '9999',
    name: 'Иван',
    age: 27,
    gender: 'male',
    preference: 'female',
    about: 'Занимаюсь силовыми, ищу партнёра по тренировкам',
    photos: ['https://i.pravatar.cc/400?img=12'],
    city: 'Москва',
    club: 'FitLife',
    active: true,
  },
  {
    user_id: '1001',
    name: 'Анна',
    age: 25,
    gender: 'female',
    preference: 'male',
    about: 'Люблю кроссфит и здоровое питание',
    photos: ['https://i.pravatar.cc/400?img=1'],
    city: 'Москва',
    club: 'FitLife',
    active: true,
  },
  {
    user_id: '1002',
    name: 'Мария',
    age: 28,
    gender: 'female',
    preference: 'male',
    about: 'Йога и плавание — моё всё',
    photos: ['https://i.pravatar.cc/400?img=2'],
    city: 'Москва',
    club: 'SportCity',
    active: true,
  },
  {
    user_id: '1003',
    name: 'Елена',
    age: 23,
    gender: 'female',
    preference: 'any',
    about: 'Бег и функциональный тренинг',
    photos: ['https://i.pravatar.cc/400?img=3', 'https://i.pravatar.cc/400?img=5'],
    city: 'Санкт-Петербург',
    club: 'FitLife',
    active: true,
  },
  {
    user_id: '1004',
    name: 'Дарья',
    age: 30,
    gender: 'female',
    preference: 'male',
    about: 'Тяжёлая атлетика и пауэрлифтинг',
    photos: ['https://i.pravatar.cc/400?img=6'],
    city: 'Москва',
    club: 'FitLife',
    active: true,
  },
  {
    user_id: '1005',
    name: 'Ксения',
    age: 26,
    gender: 'female',
    preference: 'male',
    about: 'Зумба и растяжка',
    photos: ['https://i.pravatar.cc/400?img=7'],
    city: 'Казань',
    club: 'ActiveClub',
    active: true,
  },
]
